### ISSUE TITLE
Debug cuda code

### ISSUE THREAD

**Issue by gwen233666** [lihaolin88/3D-Half-Gaussian-Splatting#3]
Hello, how do you debug cuda code when you add normal parameters? I also want to add some new attributes to gaussians, but I don't know how to add them, which makes me very upset. Can you give me some suggestions? Appreciate very much~

**Comment by lihaolin88** [comment]
Hello, this is a good question. Debugging code during training or testing can be challenging. There are two approaches you can consider:

1. Save the result from the Python code and use it as input for CUDA code, you can then use cuda-gdb to debug the code. This allows you to only run the CUDA part and set breakpoints.

2. Use "printf" in the CUDA code. This method involves printing out the data you want to check. While simple and effective for inspecting the entire pipeline, it requires careful design of the architecture and considerate tracking of changes and expected outputs.

To add new attributes, I recommend looking through ./scene/gaussian_model.py and especially paying attention to the "init" functions. Then, you will have some ideas on how to add new attributes to Gaussians.

**Comment by gwen233666** [comment]
Hello, when I used the original 3dgs code to reproduce the code of the new attribute, I encountered such a problem, but I do not know how to solve it. Have you ever encountered similar problems when creating 3dhgs? Any good solutions, thank you.

![image](https://github.com/lihaolin88/3D-Half-Gaussian-Splatting/assets/130142345/94cdfde7-cb4a-42e1-a79d-b227fcefb396)

Training progress:   0%|          | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\ZWD\3DGS\3DGS-master\train.py", line 242, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "D:\ZWD\3DGS\3DGS-master\train.py", line 89, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "D:\ZWD\3DGS\3DGS-master\gaussian_renderer\__init__.py", line 132, in render
    "visibility_filter" : radii > 0,
RuntimeError: CUDA error: an illegal memory access was encountered
Training progress:   0%|          | 0/30000 [00:00<?, ?it/s]

**Comment by lihaolin88** [comment]
Hello,

It seems like there are some issues with your rasterizer, and from the error message, I recommend you set a breakpoint in "/gaussian_rennderer/__init__.py" line 132 to see if the variable 'radii' is correct. I also recommend you to add some "printf" in your cuda code to ensure all the variables are same as your expect.

Best,

Haolin Li
