### ISSUE TITLE
class DoGFilter(nn.Module):  def apply_dog_filter(batch, freq=50, scale_factor=0.5):

### ISSUE THREAD

**Issue by bysb** [lihaolin88/3D-Half-Gaussian-Splatting#6]
Hi !  
I am confused when reading the code here, and I have not found ‘’class DoGFilter(nn.Module)‘’ and ‘’def apply_dog_filter(batch, freq=50, scale_factor=0.5) ‘’ being called elsewhere. How are they understood?  Thanks for you help.

**Comment by lihaolin88** [comment]
Hello, Thank you for your interest in our work! The "DoGFilter" function is defined in "half_gaussian_project/utils/image_utils.py." This function is used to apply a Difference of Gaussians (DoG) filter to a batch of images.

**Comment by bysb** [comment]
Thank you for your reply! May I ask how this module (The "DoGFilter" function) is called during code execution？

**Comment by lihaolin88** [comment]
Hello, no problem! "DoGFilter" is a function from the original 3D Gaussian splatting project. It can be used to smooth or sharpen the input image. However, this function was not used in the original method. If you want to apply this function, you can use it in "half_gaussian_splatting_project/scene/dataset_readers.py".
